ARG version=latest
#FROM arcor2/arcor2_base:$version

#COPY . /root/arcor2/

#RUN cd ~/arcor2 \
#	&& ./pants package src/python/arcor2_calibration/scripts:calibration

FROM arcor2/arcor2_dist_base:$version

RUN apt-get update \      
    && apt-get install -y libgl1-mesa-glx libglib2.0-0 libgomp1 libusb-1.0-0 \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY src.python.arcor2_calibration.scripts/calibration.pex /root/calibration.pex

COPY docker/start-calibration.sh ./start.sh