ARG version=latest
#FROM arcor2/arcor2_base:$version

#COPY . /root/arcor2/

#RUN cd ~/arcor2 \
#	&& ./pants package src/python/arcor2_execution/scripts:execution

FROM arcor2/arcor2_dist_base:$version

RUN mkdir -p /root/project

COPY src.python.arcor2_execution.scripts/execution.pex /root/execution.pex

RUN apt-get update \
        && apt-get install -y -q libgl1-mesa-glx libglib2.0-0 \
        && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY docker/start-execution.sh ./start.sh

EXPOSE 6790
